### PR TITLE
Create AWX Operator version file

### LINKED ISSUE #22: Helm chart versioning
Current discussion ongoing in the forum about versioning the helm chart: https://forum.ansible.com/t/awx-operator-helm-versioning/8228

The purpose of this issue is to track the discussion so we have a link to the outcome captured somewhere in this repo. If you have comments or input on the versioning, please add your thoughts to the forum topic.

This also relates to https://github.com/ansible-community/awx-operator-helm/issues/7 but that is specific to the borked ci check, which is something we can fix after we figure out the new versioning.

### PR DESCRIPTION
**Pull request by oraNod**
Resolves #22 

- Adds `awx-operator-version.txt` that captures the version of the AWX Operator (repo tag).
- Updates the makefile to set the AWX Operator version from the txt file.
- Updates the clone script to use the txt file when grafting relevant parts of the AWX Operator repo.

### CODE REVIEW

**Comment by miles-w-3** [comment]
@oraNod I think it makes sense to use the helm-starter `Chart.yaml` [here](https://github.com/ansible-community/awx-operator-helm/blob/main/.helm/starter/Chart.yaml) as the source of truth for versioning. Annoyingly, the helm init command using a starter does not inherit those version fields, but we could use `yq` to copy them in from the starter chart.yaml into the main one. Under this system, `appVersion` would be the version of AWX Operator as the app being installed by the chart, and then `version` would be our separately maintainable field that we can increment for our other proposals like adding labels, annotations, controller field overrides, etc.

I'm happy to create a PR proposal if that's easier

**Comment by oraNod** [comment]
> @oraNod I think it makes sense to use the helm-starter `Chart.yaml` [here](https://github.com/ansible-community/awx-operator-helm/blob/main/.helm/starter/Chart.yaml) as the source of truth for versioning. Annoyingly, the helm init command using a starter does not inherit those version fields, but we could use `yq` to copy them in from the starter chart.yaml into the main one. Under this system, `appVersion` would be the version of AWX Operator as the app being installed by the chart, and then `version` would be our separately maintainable field that we can increment for our other proposals like adding labels, annotations, controller field overrides, etc.
> 
> I'm happy to create a PR proposal if that's easier

@miles-w-3 Thanks for this suggestion! It does seem like the right place for a source of truth. I was honestly thinking that the solution I've put together in this PR might be a bit hack-y so I really appreciate you pointing this out and steering towards something less clunky. This could also remove the need to create tags.

I certainly don't mind you creating a PR proposal. I'm happy to do that too but will step back and let you go for it. Cheers.

**Comment by miles-w-3** [comment]
@oraNod Sorry for the delay, please see https://github.com/ansible-community/awx-operator-helm/pull/25 

This may also be out of scope for this PR, but there's an opportunity for us to do a lot less work around the releases with chart-releaser. We couldn't use it before fully since it was part of the larger repo but it might help, there's a comment on it here: https://github.com/ansible-community/awx-operator-helm/blob/b55810646fd3d88764df9f3bf3d0bb016e22741c/Makefile#L192

**Comment by oraNod** [comment]
@miles-w-3 No worries at all about the delay. I was out last week doing family stuff. I'll go ahead and close this PR as your alternative is much better (and less hacky).

That also sounds good about using chart-releaser. Seems like a better way to do things (but, yeah, as a follow on). Thanks for pointing that out!

**Pull request closed without merging**
